apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-page-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signup-page
  template:
    metadata:
      labels:
        app: signup-page
    spec:
      containers:
      - name: signup-page
        image: __IMAGE__
        ports:
        - containerPort: 80
